{
   "before_install" : "true",
   "env" : {
      "global" : {
         "secure" : "npB7yga9waVkKii5Bnw61JErom95fHkB8VZbSSely0JqLyX5VXAagaJyAv3QYEhhfRKOobyccvtX1F09bcAJqjZvLmHVZ29Wm91OYO9G0yxp7/TgqQGspf2R6dPiqKLtbJPKOmIEawhVm7zo8fdK8nR2\u002Bz/XRZdLkWLzYAcHwoE="
      }
   },
   "git" : {
      "submodules" : false
   },
   "install" : "make test-deps",
   "jobs" : {
      "include" : [
         {
            "stage" : "test"
         },
         {
            "before_install" : "true",
            "install" : "true",
            "script" : "curl -f https://gist.githubusercontent.com/wakaba/ab553f86cd017e0cb28c6dbb5364b009/raw/travis-merge-job.pl | perl",
            "stage" : "merge"
         }
      ]
   },
   "language" : "perl",
   "notifications" : {
      "email" : [
         "wakaba@suikawiki.org"
      ],
      "irc" : {
         "channels" : [
            "ircs://irc.suikawiki.org:6697#mechanize"
         ],
         "use_notice" : true
      }
   },
   "perl" : [
      "5.32"
   ],
   "script" : "make test"
}
