{
   "concurrency" : {
      "cancel-in-progress" : true,
      "group" : "pages"
   },
   "jobs" : {
      "deploy" : {
         "environment" : {
            "name" : "github-pages",
            "url" : "${{ steps.deployment.outputs.page_url }}"
         },
         "if" : "${{ github.event.workflow_run.conclusion == 'success' }}",
         "runs-on" : "ubuntu-latest",
         "steps" : [
            {
               "name" : "Checkout",
               "uses" : "actions/checkout@v2"
            },
            {
               "run" : "make build-github-pages"
            },
            {"run": "du -c -s -h *"}
         ]
      }
   },
   "name" : "pages",
   "on" : {
      "workflow_run" : {
         "branches" : [
            "master"
         ],
         "types" : [
            "completed"
         ],
         "workflows" : [
            "test"
         ]
      }
   },
   "permissions" : {
      "contents" : "read",
      "id-token" : "write",
      "pages" : "write"
   }
}
